services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: cornifer
    ports:
      - "3306:3306"
    volumes:
      - my-db-volume:/var/lib/mysql
    secrets:
      - db_root_password

secrets:
  db_root_password:
    file: db_root_password.txt

volumes:
  my-db-volume: